version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bFamvo9gdBj3p7L
      MYSQL_DATABASE: product_db
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  mariadb:
